### PR TITLE
Init: wish and 3 rules #13

### PR DESCRIPTION
**Pull request by eeuih**
1. Introduce your 3 rules to other
2. Get an approval from a total of 3 people.

### CODE REVIEW

**Review by zeze95 — APPROVED** [review]
함께 화이팅해요!!

**Review by mijeongkim3 — APPROVED** [review]
모르는거 잘 도와주셔서 감사해용~^_^!!! 화이팅!

**Review by zeze95 — APPROVED** [review]
괜찮아요 화이팅!!!

**Review by ome-r — APPROVED** [review]
취업 이룹시다!!!

**Pull request merged**
