### PR TITLE
Init: wish and 3 rules #17

### PR DESCRIPTION
**Pull request by mijeongkim3**
1. Introduce your 3 rules to other
2. Get an approval from a total of 3 people.

### CODE REVIEW

**Review by eeuih — APPROVED** [review]
화이팅입니닷~~!!

**Review by zeze95 — APPROVED** [review]
함께 열심히해요!!!

**Comment by chaeyeongLEE** [comment]
함께 화이팅입니다 아잣 :)

**Review by chaeyeongLEE — APPROVED** [review]
함께 화이팅입니다 :) ♥

**Pull request merged**
