### PR TITLE
Init: wish and 3 rules #25

### PR DESCRIPTION
**Pull request by boseungdl**
1. Introduce your 3 rules to other
2. Get an approval from a total of 3 people.

### CODE REVIEW

**Review by nanannannana — APPROVED** [review]
응원합니다!

**Review by jihyang1106 — APPROVED** [review]
6커밋 화이팅입니다잉

**Review by SeoHaeRi — APPROVED** [review]
응원하겠습니다~!

**Review by ghost — APPROVED** [review]
화잍이입니다

**Pull request merged**
