### PR TITLE
Init: wish and 3 rules #28

### PR DESCRIPTION
**Pull request by hyonie-Kim**
1. Introduce your 3 rules to other
2. Get an approval from a total of 3 people.

### CODE REVIEW

**Review by nietzche15 — APPROVED** [review]
함께 열심히 해봐요!

**Review by HeeyoungJ — APPROVED** [review]
4월까지 함께 열심히 해보아요~!

**Review by nietzche15 — APPROVED** [review]
함께 열심히 해봐요!

**Review by SeoHaeRi — APPROVED** [review]
응원할게요~~

**Pull request merged**
