### PR TITLE
Init: wish and 3 rules #12

### PR DESCRIPTION
**Pull request by SeoHaeRi**
1. Introduce your 3 rules to other
2. Get an approval from a total of 3 people.

### CODE REVIEW

**Comment by nyondoo** [comment]
리뷰~!

**Review by imphm — APPROVED** [review]
파이팅

**Review by nyondoo — APPROVED** [review]
리뷰입니다~!

**Review by ghost — APPROVED** [review]
굿입니다

**Review by GSIII — APPROVED** [review]
반갑습니다!취업 화이팅~~~

**Pull request merged**
