### PR TITLE
Init: wish and 3 rules #22

### PR DESCRIPTION
**Pull request by jihyang1106**
1. Introduce your 3 rules to other
2. Get an approval from a total of 3 people.

### CODE REVIEW

**Comment by doch2130** [comment]
앞자리에요 잘부탁드려요~

**Review by jihyang1106 — COMMENTED** [review]
화이팅 ❤️

**Review by doch2130 — APPROVED** [review]
앞자리에요 잘부탁드려요

**Review by boseungdl — APPROVED** [review]
앞으로 잘 지내봐요~

**Review by GSIII — APPROVED** [review]
반가워용!!! 취뽀 화이팅~~~~

**Pull request merged**
